### ISSUE TITLE
Life stages section of connect page

### ISSUE THREAD

**Issue by xumaple** [hmcc-global/hmccaa-web#174]
![image](https://github.com/hmcc-global/hmccaa-web/assets/45406854/0f09bfce-fd05-4085-a73d-637a7f10bf1a)
see figma for more details

*also include the hgames picture in this work item*

**Comment by initialdpw** [comment]
fyi, the idea was to have a separate page for each life stage specifically so ppl can see more details on a particular group. maybe in future, we can.

not sure if it's too complicated but can link each of those cards to the specific location of the life stage page? i.e. if you click on Access, it'll go to the Life Stage page below, but already scrolled down to the Access section, instead of the top of that page.

![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/cc76981b-f884-4258-9525-6bb95a1b9972)

**Comment by initialdpw** [comment]
@xumaple i'm going to close this issue as we're planning to merge the CONNECT and I'M NEW pages, this section will be deleted. Ideally, still want the page dedicated to the LIFE stages as we see in the screenshot above. 

this page would be linked from home and from i'm new.
