### ISSUE TITLE
[Next Steps] Buttons for each LG stage sign up 

### ISSUE THREAD

**Issue by Brandt-Bowling** [hmcc-global/hmccaa-web#263]
Similar to existing site
![Screenshot_20240525-110105.png](https://github.com/hmcc-global/hmccaa-web/assets/16947840/438aecfc-4ed2-4fc5-88a3-ca8237a4303f)

**Comment by terrianx** [comment]
do these buttons replace "check out a life group"?
<img width="1440" alt="Screenshot 2024-06-09 at 7 12 34 PM" src="https://github.com/hmcc-global/hmccaa-web/assets/88253868/b43066f4-73bd-46f5-bd9c-2a17fe38e1bc">

**Comment by initialdpw** [comment]
hmms, let me try to clarify with pjosh if we can have 1 form only. i'm not sure if we need ALL 4 forms. don't see why we cannot have 1 form and based on how ppl answer on page 1, split into different sections based on life stages. having multiple buttons all looking the same is kind of confusing and not good UX.

**Comment by initialdpw** [comment]
thanks for your patienceeeeee. so for now, we'll need to keep Undergrad google form link separate but can combine the rest. updated the figma but some comments:

Can we have the first button jump to the bottom 2 buttons when someone clicks on it?
![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/547c9aba-6c73-4c58-9a3b-5be223021a06)

Bottom two buttons
![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/eca18c14-a432-4295-b894-79b7797d679d)

Hope that makes sense. let me know if you have questions

**Comment by terrianx** [comment]
thanks for getting back to this. the last button on the old website is the same link as the one "check out a lifegroup" on the new website. im assuming there should be a separate link somewhere?

**Comment by initialdpw** [comment]
not sure the question but for new website, the two blue buttons on bottom:
1. LG SIGN UP: UNDERGRAD STUDENTS - https://docs.google.com/forms/d/e/1FAIpQLSd85EV0Vw9ucYW9YOEsWaoRvl4jvWjmy0uJpASlMtpz8GRyug/viewform
2. LG SIGN UP: ALL OTHER LIFE STAGES - https://docs.google.com/forms/d/e/1FAIpQLSeSKeuDEtmv9mQAmm603df8IW82Uq6g_kiIKp-QnsUdBNcZbQ/viewform

And for the white button "CHECK OUT A LIFE GROUP" of new website, can we make it so that when ppl click on it, it scrolls down the page to those 2 blue buttons? otherwise, probably better to remove it.
